"""
majority_vote.py

MajorityPUF(C, 9) from Eq. (3): reduces nine raw comparator readings per
challenge to one majority-voted response bit,

    R_l = Maj( PUF(c_l)^(1), ..., PUF(c_l)^(9) ),   l = 1..q, q = 1023.

This module only does the reduction. It does not generate raw reads:
those come either from real HSpice-exported comparator records (Task C,
the entropy/co-simulation analysis) or, for the Table 17 Raspberry Pi
latency benchmark (Task A), from synthetic same-shaped stand-in data
generated by the benchmark harness itself and explicitly labeled as
such. See benchmark_table17.py's module docstring for why a synthetic
input is appropriate there and would NOT be appropriate for Task C.
"""

READS_PER_CHALLENGE = 9
NUM_CHALLENGES = 1023
RESPONSE_BYTES = (NUM_CHALLENGES + 7) // 8  # 128 bytes; last 1 bit unused/zero


def majority_vote(reads: list[list[int]]) -> bytes:
    """
    reads: NUM_CHALLENGES lists (one per challenge), each of
    READS_PER_CHALLENGE 0/1 ints (one per comparator read).

    Returns the majority-voted response vector R, packed big-endian into
    RESPONSE_BYTES bytes (bit 0 = MSB of byte 0), one bit per challenge,
    trailing padding bit fixed at 0.
    """
    if len(reads) != NUM_CHALLENGES:
        raise ValueError(f"expected {NUM_CHALLENGES} challenges, got {len(reads)}")

    out_bits = 0
    for challenge_reads in reads:
        if len(challenge_reads) != READS_PER_CHALLENGE:
            raise ValueError(
                f"expected {READS_PER_CHALLENGE} reads per challenge, "
                f"got {len(challenge_reads)}"
            )
        ones = sum(challenge_reads)
        bit = 1 if ones > (READS_PER_CHALLENGE // 2) else 0
        out_bits = (out_bits << 1) | bit

    out_bits <<= (RESPONSE_BYTES * 8 - NUM_CHALLENGES)  # pad to byte boundary
    return out_bits.to_bytes(RESPONSE_BYTES, "big")
